project:
  type: manuscript
  render:
    - "*.qmd"
    - "notebooks/*.qmd"
    - "!legacy/"
    - "!templates/"

manuscript:
  article: index.qmd
  notebooks:
    - notebook: notebooks/notebook-01.qmd
      title: "Example of Python Analysis"
    - notebook: notebooks/notebook-02.qmd
      title: "Example of R Analysis"
    - notebook: notebooks/notebook-03.qmd
      title: "Example of Stata Analysis"

format:
  html:
    theme: cosmo
    highlight-style: github
    toc: true
    toc-depth: 3
    code-fold: false
    code-tools: true
    lightbox: true
    citation-location: document
    css: styles.css

  pdf:
    documentclass: scrartcl
    papersize: letter
    number-sections: true
    colorlinks: true
    keep-tex: true
    notebook-links: false

  docx:
    notebook-links: false

execute:
  freeze: auto

editor: visual
