---
title: "Descriptive statistics from stargazer"
author: "Carlos Mendez"
date: "5/29/2020"
output:
  word_document: default
  pdf_document:
    includes:
      in_header: preamble.tex
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  cache=TRUE,
  messages=FALSE,
  warning=FALSE,
  out.width = "95%")
library(tidyverse)
library(knitr)
options(digits = 2)
options(scipen = 999)
options(kableExtra.auto_format = FALSE) 
library(kableExtra)
library(xtable)
library(stargazer)
```


## Descriptive statistics

### Latex

```{r }
## attitude is a df
stargazer(attitude,
          covariate.labels=c("The Rating",
                   "Handling of Complaints",
                   "No Special Privileges",
                   "Opportunity to Learn",
                   "Performance-Based Raises",
                   "Too Critical",
                   "Advancement",
                   "Very High Rating"),
          title="Descriptive statistics",
          notes = "Notes: Here are some notes",
          median = TRUE,
          iqr = FALSE,
          digits = 2,
          align = TRUE,
          type = "text",
          no.space = TRUE,
          out = "../results/tab-descriptiveStats.tex")
```





## Regression models


### Latex

```{r }
## 2 OLS models
linear.1 <- lm(rating ~ complaints + privileges + learning + raises + critical, data=attitude)
linear.2 <- lm(rating ~ complaints + privileges + learning, data=attitude)
 
## create an indicator dependent variable, and run a probit model
 
attitude$high.rating <- (attitude$rating > 70)
probit.model <- glm(high.rating ~ learning + critical + advance, data=attitude, family = binomial(link = "probit"))
 
stargazer(linear.1, linear.2, probit.model, title="Regression Results", align=TRUE)
```



### Latex with longer names 

```{r}
stargazer(linear.1, linear.2, probit.model, title="Regression Results", align=TRUE, dep.var.labels=c("Overall Rating","High Rating"), covariate.labels=c("Handling of Complaints","No Special Privileges", "Opportunity to Learn","Performance-Based Raises","Too Critical","Advancement"), omit.stat=c("LL","ser","f"), no.space=TRUE)
```




### Text

```{r}
stargazer(linear.1, linear.2, probit.model, type="text", title="Regression Results", align=TRUE)
```

### Text

```{r}
stargazer(linear.1, linear.2, probit.model, type="html", title="Regression Results", align=TRUE)
```

### HTML 

```{r, results= "asis"}
stargazer(linear.1, linear.2, probit.model, type="html", title="Regression Results", align=TRUE)
```

### Export latex table

```{r, results= "asis"}
stargazer(linear.1, linear.2, probit.model,
          title="Regression Results",
          align=TRUE,
          type = "html",
          no.space = TRUE,
          out = "../results/table.tex")
```


### Export html table


```{r}
stargazer(linear.1, linear.2, probit.model,
          title="Regression Results",
          align=TRUE,
          type = "text",
          no.space = TRUE,
          out = "../results/table.html")
```


### Export text table


```{r}
stargazer(linear.1, linear.2, probit.model,
          title="Regression Results",
          align=TRUE,
          type = "text",
          no.space = TRUE,
          out = "table.text")
```


## Input external tables

### From latex code

<!-- To compile to pdf add the following:  \input{table.tex} -->


### From html code

```{r eval=T, echo=FALSE}
htmltools::includeHTML("table.html")
```

## Word tables

```{r eval=T, echo=FALSE}
stargazer(linear.1, linear.2, probit.model,
          title="Regression Results",
          align=TRUE,
          type = "text",
          no.space = TRUE,
          out = "table.text")
```



